### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by suzumasa96** [suzumasa96/furima3-31955#10]
# URL
 https://furima-31955.herokuapp.com/
# Basic認証のIDとパスワード
 ID: admin PASS: 8888
# 出品者用のメールアドレスとパスワード
 email: sample@sample.com PASS:m123456
# 購入者用のメールアドレスとパスワード
 email: sample1@sample.com PASS: s123456
# 購入用カードの番号・期限・セキュリティコード
 カード番号：4242424242424242　期限：3/30　セキュリティコード：123

**Comment by mo1015** [comment]
鈴木さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**○パスワードは、半角英数字混合での入力を必須としましょう
○適切では無い値が入力された場合、エラーメッセージを出力させるようにしましょう**（ユーザー管理機能、商品出品機能、商品編集機能にてエラーメッセージが出力されません）
**○出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう**(出品者が編集ページへ遷移、編集できてしまいます)


修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
再度のご提出ありがとうございます‼︎
動作の確認をしたところ、前回指摘した点については修正が確認できました。
引き続き、修正していただきたい箇所がございましたので、以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **商品詳細ページにて、ログアウト状態のユーザーには、「購入画面に進むボタン」が表示されないようにしましょう**
現状、ログアウト状態のユーザーにも「購入画面に進むボタン」が表示されてしまっています。

- [x] **ログイン状態の出品者以外のユーザーは、URLを直接入力して出品していない商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう**
現状、出品者以外のユーザーが編集ページに遷移できてしまいます。

- [x] **ログイン状態の出品者でも、売却済みの商品に対しては「編集・削除ボタン」が表示されないようにしましょう**
現状、売却済みの商品に対しても「編集・削除ボタン」が表示されてしまっています。
<img width="1440" alt="スクリーンショット 2020-12-14 16 15 25" src="https://user-images.githubusercontent.com/54050089/102051798-76579f80-3e28-11eb-83cb-074f578184ec.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
再度のご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**[補足]**
ユーザー新規登録ページにて、最初からエラーメッセージが表示されてしまっています。可能であれば、こちらは修正しておきましょう。
<img width="1440" alt="スクリーンショット 2020-12-14 17 06 12" src="https://user-images.githubusercontent.com/54050089/102057141-cfc3cc80-3e30-11eb-8af2-d6d6fdef4200.png">

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/54050089/102057355-229d8400-3e31-11eb-99ba-dd375caaf5cc.png)
